import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy policy",
  description: "How Conspire LLC collects, uses and protects information in connection with the Bonde Shopify app.",
  alternates: { canonical: "/privacy" },
};

/**
 * Bonde app privacy policy. Source of truth is PRIVACY_POLICY.docx in the
 * Bonde app repo (effective 2026-04-25); this copy drops the AI Strategist /
 * Anthropic processing sections because that feature was switched off in
 * September 2026. Legal text — review before changing further.
 */
export default function PrivacyPage() {
  return (
    <section className="bonde-section scheme-cream bonde-page">
      <div className="bonde-inner bonde-prose">
        <h1 className="bonde-h1">Bonde privacy policy</h1>
        <p className="bonde-prose__meta">Effective date: September 24, 2026 (supersedes April 25, 2026)</p>
        <h2>1. Introduction</h2>
        <p>This Privacy Policy explains how Conspire LLC (&quot;Conspire,&quot; &quot;we,&quot; &quot;us,&quot; or &quot;our&quot;) collects, uses, shares, and protects information in connection with the Bonde Shopify application and related services (collectively, &quot;Bonde&quot; or the &quot;App&quot;). Bonde is installed by Shopify merchants (each a &quot;Merchant&quot;) on their Shopify stores to provide subscriptions, upsells, free gifts, bundling, merchandising, order tracking pages, transactional email, and analytics features.</p>
        <p>Bonde processes two broad categories of information: (a) information about Merchants and their personnel (the &quot;Merchant Data&quot;), for which Conspire is the data controller; and (b) information about Merchants&apos; end customers (the &quot;End-Customer Data&quot;), for which the Merchant is the data controller and Conspire acts as a data processor or service provider on the Merchant&apos;s behalf.</p>
        <p>If you are an end customer of a Merchant who uses Bonde and have questions about how your personal information is used, please contact the Merchant directly. The Merchant&apos;s own privacy policy governs the collection and use of your personal information.</p>
        <h2>2. Who We Are</h2>
        <p>Bonde is operated by:</p>
        <p>Conspire LLC 7040 Weller St. San Diego, CA 92122 United States Email: <a href="mailto:support@conspireagency.com">support@conspireagency.com</a></p>
        <h2>3. Information We Collect</h2>
        <h3>3.1 Merchant Data</h3>
        <p>When a Merchant installs and uses Bonde, we collect:</p>
        <p>Account and store information: Shopify shop domain, store name, store ID, primary contact name and email, country, currency, timezone, plan type, and similar account-level metadata provided by Shopify during installation.</p>
        <p>Authentication and authorization data: OAuth access tokens issued by Shopify, the scopes granted to the App, and session identifiers used to authenticate the Merchant within the embedded admin.</p>
        <p>Configuration data: Settings, preferences, page builder content, themes, templates, targeting rules, discount configurations, and other content the Merchant creates or uploads while using the App.</p>
        <p>Billing data: Information necessary to process App subscription charges through Shopify&apos;s billing system. We do not collect or store payment card numbers.</p>
        <p>Support communications: Information you provide when you contact us for support, including your name, email address, and the contents of your messages.</p>
        <h3>3.2 End-Customer Data</h3>
        <p>Bonde processes information about the Merchant&apos;s end customers solely to provide the App&apos;s features to the Merchant. The categories of End-Customer Data we may process include:</p>
        <p>Customer identity: Name, email address, phone number, billing and shipping addresses, and Shopify customer ID, where this information is required to fulfill an order, render an order tracking page, send a transactional email, or compute analytics for the Merchant.</p>
        <p>Order and transaction data: Order IDs, line items, quantities, prices, discounts applied, fulfillment status, tracking numbers, carrier information, and timestamps.</p>
        <p>Subscription data: Selling plans, subscription contracts, billing attempts, retry state, and subscription lifecycle events.</p>
        <p>Cart and behavioral data: Cart line attributes used to attribute upsells, free gifts, and bundles; product impressions, clicks, and add-to-cart events generated by Bonde widgets and tracking pages.</p>
        <p>Tracking page subscribers: When an end customer voluntarily enters an email address (or other contact information) into the &quot;Subscribe to delivery updates&quot; block on a Merchant&apos;s tracking page, we store that contact information together with the associated order and an unsubscribe token in order to send delivery-status update emails on the Merchant&apos;s behalf.</p>
        <p>Derived analytics: Aggregated and customer-level rollups computed from the above data for the App’s analytics (e.g., lifetime value, order frequency, basket composition, and similar metrics).</p>
        <p>We do not knowingly collect government-issued identification numbers, payment card numbers, precise geolocation, biometric data, or special categories of personal data from end customers.</p>
        <h3>3.3 Information Collected Automatically</h3>
        <p>Log and device data: IP address, browser type, operating system, referring URL, pages viewed, and timestamps, collected when Merchants use the embedded admin or when end customers load Merchant-hosted Bonde surfaces such as tracking pages.</p>
        <p>Cookies and similar technologies: Session cookies used by Shopify App Bridge to authenticate Merchants in the embedded admin, and first-party identifiers used to measure tracking page views and engagement events. Bonde does not set advertising cookies and does not sell personal information.</p>
        <p>Error and performance data: Diagnostic information collected through our error monitoring provider (Sentry) when the App encounters errors, including stack traces, request metadata, and a redacted snapshot of the application state.</p>
        <h2>4. How We Use Information</h2>
        <p>We use the information described above to:</p>
        <p>Provide, operate, maintain, and improve the App&apos;s features for Merchants and their end customers;</p>
        <p>Authenticate Merchants and authorize requests through Shopify;</p>
        <p>Send transactional communications, including order tracking delivery-update emails to opted-in subscribers on the Merchant&apos;s behalf;</p>
        <p>Compute analytics and recommendations for Merchants;</p>
        <p>Detect, investigate, and prevent fraud, abuse, security incidents, and violations of our terms;</p>
        <p>Respond to support requests and Merchant inquiries;</p>
        <p>Comply with legal obligations and enforce our agreements;</p>
        <p>Bill Merchants for the App through Shopify&apos;s billing system.</p>
        <p>We do not use End-Customer Data to advertise to end customers, to build cross-Merchant profiles, or to train third-party machine learning models on identifiable personal data.</p>
        <h2>5. Legal Bases for Processing (EEA, UK, and Similar Jurisdictions)</h2>
        <p>Where the General Data Protection Regulation (GDPR), UK GDPR, or a similar law applies, we rely on the following legal bases to process personal data:</p>
        <p>Performance of a contract: to provide the App to the Merchant under our terms of service, and to process End-Customer Data on the Merchant&apos;s documented instructions.</p>
        <p>Legitimate interests: to secure, maintain, and improve the App; to detect and prevent fraud and abuse; and to communicate with Merchants about the App.</p>
        <p>Consent: where required (for example, when an end customer opts in to receive delivery-update emails through a tracking page subscribe block). Consent can be withdrawn at any time.</p>
        <p>Legal obligation: to comply with applicable law, including responding to lawful requests from public authorities.</p>
        <h2>7. How We Share Information</h2>
        <h3>7.1 Sub-processors</h3>
        <p>We share information with the following third-party service providers (&quot;sub-processors&quot;) that help us operate the App. Each sub-processor is bound by contractual obligations to protect personal data and to process it only on our instructions:</p>
        <p>Shopify Inc. (Canada): the platform on which the App runs; source of Merchant authentication and the originating system for most Merchant Data and End-Customer Data.</p>
        <p>Vercel Inc. (United States): application hosting and content delivery for the App&apos;s web surfaces.</p>
        <p>Neon Inc. (United States): managed PostgreSQL database hosting for the App&apos;s primary data store.</p>
        <p>Inngest Inc. (United States): background job orchestration for webhooks, scheduled tasks, and asynchronous workflows.</p>
        <p>Resend (Resend, Inc., United States): transactional email delivery, including delivery-update emails sent to tracking page subscribers.</p>
        <p>Sentry (Functional Software, Inc., United States): error monitoring and diagnostics.</p>
        <p>Meta Platforms, Inc. (United States): Conversions API event delivery, used only when the Merchant explicitly enables and configures Meta CAPI integration in the App.</p>
        <p>We may update this list from time to time. The current list reflects the sub-processors in use as of the effective date above.</p>
        <h3>7.2 Other Disclosures</h3>
        <p>We may also disclose information:</p>
        <p>To Merchants, with respect to their own End-Customer Data and configuration;</p>
        <p>To comply with applicable law, regulation, legal process, or governmental request;</p>
        <p>To enforce our terms of service or to protect the rights, property, or safety of Conspire, our Merchants, end customers, or others;</p>
        <p>In connection with a merger, acquisition, financing, reorganization, bankruptcy, or sale of all or a portion of our assets, in which case personal data may be transferred as part of the transaction, subject to the protections of this Privacy Policy.</p>
        <p>We do not sell personal information, and we do not share personal information for cross-context behavioral advertising.</p>
        <h2>8. International Data Transfers</h2>
        <p>Conspire is based in the United States, and our sub-processors are located in the United States, Canada, and other jurisdictions. If you access the App from outside the United States, your information may be transferred to, stored, and processed in the United States or other countries whose data protection laws may differ from those in your country.</p>
        <p>Where required by applicable law, we rely on appropriate safeguards for cross-border transfers of personal data, including the European Commission&apos;s Standard Contractual Clauses and equivalent mechanisms used by Shopify and our other sub-processors.</p>
        <h2>9. Data Retention</h2>
        <p>We retain Merchant Data and End-Customer Data for as long as the Merchant&apos;s installation of the App is active and for a limited period thereafter to satisfy legal, accounting, or operational requirements. When a Merchant uninstalls the App, Shopify sends us a 48-hour shop redact webhook; upon receipt, we delete the Merchant&apos;s data from our active systems in accordance with Shopify&apos;s mandatory data protection requirements.</p>
        <p>When Shopify sends us a customer redact webhook on behalf of an end customer, we delete or anonymize that end customer&apos;s personal data from our active systems, including their customer identity records, analytics rollups, and tracking page subscriber entries.</p>
        <p>End customers who opted into tracking delivery-update emails may unsubscribe at any time using the unsubscribe link included in every email; doing so suppresses further sends and removes their contact information from our active subscriber list.</p>
        <p>Aggregated, de-identified data that cannot reasonably be used to identify an individual may be retained indefinitely for analytics, model evaluation, and product improvement.</p>
        <h2>10. Your Rights</h2>
        <h3>10.1 Rights of Merchants</h3>
        <p>Merchants may access, correct, export, or delete most of their data directly through the App&apos;s admin interface or by uninstalling the App. For requests we cannot fulfill through the App, contact us at <a href="mailto:support@conspireagency.com">support@conspireagency.com</a>.</p>
        <h3>10.2 Rights of End Customers (GDPR, UK GDPR, and Similar Laws)</h3>
        <p>If you are an end customer of a Merchant that uses Bonde and you reside in the European Economic Area, the United Kingdom, or another jurisdiction with similar laws, you may have the right to:</p>
        <p>Access the personal data we hold about you;</p>
        <p>Request correction of inaccurate or incomplete personal data;</p>
        <p>Request deletion of your personal data;</p>
        <p>Object to or restrict our processing of your personal data;</p>
        <p>Request that we transfer your personal data to another service (data portability);</p>
        <p>Withdraw any consent you previously gave (such as consent to receive delivery-update emails);</p>
        <p>Lodge a complaint with your local data protection authority.</p>
        <p>Because we process End-Customer Data on the Merchant&apos;s behalf, we generally direct end customers to contact the Merchant to exercise these rights. We will assist the Merchant in responding to verified requests, and we will respond directly where required by law.</p>
        <h3>10.3 Rights of California Residents (CCPA/CPRA)</h3>
        <p>California residents have the right to know what personal information we collect, the right to request deletion, the right to correct inaccurate information, the right to limit the use of sensitive personal information, and the right not to be discriminated against for exercising these rights. We do not sell personal information and do not share personal information for cross-context behavioral advertising.</p>
        <p>California residents may submit requests through their Merchant or by emailing us at <a href="mailto:support@conspireagency.com">support@conspireagency.com</a>. We will verify requests and respond within the timeframes required by law.</p>
        <h2>11. Security</h2>
        <p>We implement administrative, technical, and physical safeguards designed to protect personal data against unauthorized access, disclosure, alteration, and destruction. These safeguards include encryption of data in transit using TLS, encryption of data at rest in our managed database, scoped OAuth tokens, signed app proxy and webhook requests, principle-of-least-privilege access controls for our personnel, and continuous error and anomaly monitoring.</p>
        <p>No method of transmission or storage is completely secure. If you have reason to believe that your interaction with the App is no longer secure, please contact us immediately at <a href="mailto:support@conspireagency.com">support@conspireagency.com</a>.</p>
        <h2>12. Children&apos;s Privacy</h2>
        <p>Bonde is intended for use by businesses and is not directed to children under the age of 16. We do not knowingly collect personal information from children. If we learn that we have collected personal information from a child without verified parental consent, we will delete that information.</p>
        <h2>13. Third-Party Sites and Services</h2>
        <p>The App may contain links to or integrate with third-party websites, services, or platforms (including Shopify itself). This Privacy Policy does not apply to those third parties, and we are not responsible for their content, privacy practices, or terms. We encourage you to review the privacy policies of any third-party services you use.</p>
        <h2>14. Changes to This Privacy Policy</h2>
        <p>We may update this Privacy Policy from time to time to reflect changes in our practices, the App, or applicable law. When we make material changes, we will update the &quot;Effective date&quot; at the top of this Policy and, where appropriate, provide additional notice to Merchants through the App or by email. Your continued use of the App after the updated Policy takes effect constitutes acceptance of the changes.</p>
        <h2>15. Contact Us</h2>
        <p>If you have questions, concerns, or requests regarding this Privacy Policy or our handling of personal data, please contact us at:</p>
        <p>Conspire LLC Attn: Privacy 7040 Weller St. San Diego, CA 92122 United States Email: <a href="mailto:support@conspireagency.com">support@conspireagency.com</a></p>
      </div>
    </section>
  );
}
